package org.blem.greek.db.model;

import java.util.ArrayList;
import java.util.List;

public class GntWordBeanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    public GntWordBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBookNameIsNull() {
            addCriterion("book_name is null");
            return (Criteria) this;
        }

        public Criteria andBookNameIsNotNull() {
            addCriterion("book_name is not null");
            return (Criteria) this;
        }

        public Criteria andBookNameEqualTo(String value) {
            addCriterion("book_name =", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameNotEqualTo(String value) {
            addCriterion("book_name <>", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameGreaterThan(String value) {
            addCriterion("book_name >", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameGreaterThanOrEqualTo(String value) {
            addCriterion("book_name >=", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameLessThan(String value) {
            addCriterion("book_name <", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameLessThanOrEqualTo(String value) {
            addCriterion("book_name <=", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameLike(String value) {
            addCriterion("book_name like", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameNotLike(String value) {
            addCriterion("book_name not like", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameIn(List<String> values) {
            addCriterion("book_name in", values, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameNotIn(List<String> values) {
            addCriterion("book_name not in", values, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameBetween(String value1, String value2) {
            addCriterion("book_name between", value1, value2, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameNotBetween(String value1, String value2) {
            addCriterion("book_name not between", value1, value2, "bookName");
            return (Criteria) this;
        }

        public Criteria andChapterIsNull() {
            addCriterion("chapter is null");
            return (Criteria) this;
        }

        public Criteria andChapterIsNotNull() {
            addCriterion("chapter is not null");
            return (Criteria) this;
        }

        public Criteria andChapterEqualTo(Integer value) {
            addCriterion("chapter =", value, "chapter");
            return (Criteria) this;
        }

        public Criteria andChapterNotEqualTo(Integer value) {
            addCriterion("chapter <>", value, "chapter");
            return (Criteria) this;
        }

        public Criteria andChapterGreaterThan(Integer value) {
            addCriterion("chapter >", value, "chapter");
            return (Criteria) this;
        }

        public Criteria andChapterGreaterThanOrEqualTo(Integer value) {
            addCriterion("chapter >=", value, "chapter");
            return (Criteria) this;
        }

        public Criteria andChapterLessThan(Integer value) {
            addCriterion("chapter <", value, "chapter");
            return (Criteria) this;
        }

        public Criteria andChapterLessThanOrEqualTo(Integer value) {
            addCriterion("chapter <=", value, "chapter");
            return (Criteria) this;
        }

        public Criteria andChapterIn(List<Integer> values) {
            addCriterion("chapter in", values, "chapter");
            return (Criteria) this;
        }

        public Criteria andChapterNotIn(List<Integer> values) {
            addCriterion("chapter not in", values, "chapter");
            return (Criteria) this;
        }

        public Criteria andChapterBetween(Integer value1, Integer value2) {
            addCriterion("chapter between", value1, value2, "chapter");
            return (Criteria) this;
        }

        public Criteria andChapterNotBetween(Integer value1, Integer value2) {
            addCriterion("chapter not between", value1, value2, "chapter");
            return (Criteria) this;
        }

        public Criteria andVerseIsNull() {
            addCriterion("verse is null");
            return (Criteria) this;
        }

        public Criteria andVerseIsNotNull() {
            addCriterion("verse is not null");
            return (Criteria) this;
        }

        public Criteria andVerseEqualTo(Integer value) {
            addCriterion("verse =", value, "verse");
            return (Criteria) this;
        }

        public Criteria andVerseNotEqualTo(Integer value) {
            addCriterion("verse <>", value, "verse");
            return (Criteria) this;
        }

        public Criteria andVerseGreaterThan(Integer value) {
            addCriterion("verse >", value, "verse");
            return (Criteria) this;
        }

        public Criteria andVerseGreaterThanOrEqualTo(Integer value) {
            addCriterion("verse >=", value, "verse");
            return (Criteria) this;
        }

        public Criteria andVerseLessThan(Integer value) {
            addCriterion("verse <", value, "verse");
            return (Criteria) this;
        }

        public Criteria andVerseLessThanOrEqualTo(Integer value) {
            addCriterion("verse <=", value, "verse");
            return (Criteria) this;
        }

        public Criteria andVerseIn(List<Integer> values) {
            addCriterion("verse in", values, "verse");
            return (Criteria) this;
        }

        public Criteria andVerseNotIn(List<Integer> values) {
            addCriterion("verse not in", values, "verse");
            return (Criteria) this;
        }

        public Criteria andVerseBetween(Integer value1, Integer value2) {
            addCriterion("verse between", value1, value2, "verse");
            return (Criteria) this;
        }

        public Criteria andVerseNotBetween(Integer value1, Integer value2) {
            addCriterion("verse not between", value1, value2, "verse");
            return (Criteria) this;
        }

        public Criteria andSequenceIsNull() {
            addCriterion("sequence is null");
            return (Criteria) this;
        }

        public Criteria andSequenceIsNotNull() {
            addCriterion("sequence is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceEqualTo(Integer value) {
            addCriterion("sequence =", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotEqualTo(Integer value) {
            addCriterion("sequence <>", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceGreaterThan(Integer value) {
            addCriterion("sequence >", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceGreaterThanOrEqualTo(Integer value) {
            addCriterion("sequence >=", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceLessThan(Integer value) {
            addCriterion("sequence <", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceLessThanOrEqualTo(Integer value) {
            addCriterion("sequence <=", value, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceIn(List<Integer> values) {
            addCriterion("sequence in", values, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotIn(List<Integer> values) {
            addCriterion("sequence not in", values, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceBetween(Integer value1, Integer value2) {
            addCriterion("sequence between", value1, value2, "sequence");
            return (Criteria) this;
        }

        public Criteria andSequenceNotBetween(Integer value1, Integer value2) {
            addCriterion("sequence not between", value1, value2, "sequence");
            return (Criteria) this;
        }

        public Criteria andTextIsNull() {
            addCriterion("text is null");
            return (Criteria) this;
        }

        public Criteria andTextIsNotNull() {
            addCriterion("text is not null");
            return (Criteria) this;
        }

        public Criteria andTextEqualTo(String value) {
            addCriterion("text =", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextNotEqualTo(String value) {
            addCriterion("text <>", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextGreaterThan(String value) {
            addCriterion("text >", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextGreaterThanOrEqualTo(String value) {
            addCriterion("text >=", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextLessThan(String value) {
            addCriterion("text <", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextLessThanOrEqualTo(String value) {
            addCriterion("text <=", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextLike(String value) {
            addCriterion("text like", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextNotLike(String value) {
            addCriterion("text not like", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextIn(List<String> values) {
            addCriterion("text in", values, "text");
            return (Criteria) this;
        }

        public Criteria andTextNotIn(List<String> values) {
            addCriterion("text not in", values, "text");
            return (Criteria) this;
        }

        public Criteria andTextBetween(String value1, String value2) {
            addCriterion("text between", value1, value2, "text");
            return (Criteria) this;
        }

        public Criteria andTextNotBetween(String value1, String value2) {
            addCriterion("text not between", value1, value2, "text");
            return (Criteria) this;
        }

        public Criteria andNormalizedTextIsNull() {
            addCriterion("normalized_text is null");
            return (Criteria) this;
        }

        public Criteria andNormalizedTextIsNotNull() {
            addCriterion("normalized_text is not null");
            return (Criteria) this;
        }

        public Criteria andNormalizedTextEqualTo(String value) {
            addCriterion("normalized_text =", value, "normalizedText");
            return (Criteria) this;
        }

        public Criteria andNormalizedTextNotEqualTo(String value) {
            addCriterion("normalized_text <>", value, "normalizedText");
            return (Criteria) this;
        }

        public Criteria andNormalizedTextGreaterThan(String value) {
            addCriterion("normalized_text >", value, "normalizedText");
            return (Criteria) this;
        }

        public Criteria andNormalizedTextGreaterThanOrEqualTo(String value) {
            addCriterion("normalized_text >=", value, "normalizedText");
            return (Criteria) this;
        }

        public Criteria andNormalizedTextLessThan(String value) {
            addCriterion("normalized_text <", value, "normalizedText");
            return (Criteria) this;
        }

        public Criteria andNormalizedTextLessThanOrEqualTo(String value) {
            addCriterion("normalized_text <=", value, "normalizedText");
            return (Criteria) this;
        }

        public Criteria andNormalizedTextLike(String value) {
            addCriterion("normalized_text like", value, "normalizedText");
            return (Criteria) this;
        }

        public Criteria andNormalizedTextNotLike(String value) {
            addCriterion("normalized_text not like", value, "normalizedText");
            return (Criteria) this;
        }

        public Criteria andNormalizedTextIn(List<String> values) {
            addCriterion("normalized_text in", values, "normalizedText");
            return (Criteria) this;
        }

        public Criteria andNormalizedTextNotIn(List<String> values) {
            addCriterion("normalized_text not in", values, "normalizedText");
            return (Criteria) this;
        }

        public Criteria andNormalizedTextBetween(String value1, String value2) {
            addCriterion("normalized_text between", value1, value2, "normalizedText");
            return (Criteria) this;
        }

        public Criteria andNormalizedTextNotBetween(String value1, String value2) {
            addCriterion("normalized_text not between", value1, value2, "normalizedText");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andMorphTagIsNull() {
            addCriterion("morph_tag is null");
            return (Criteria) this;
        }

        public Criteria andMorphTagIsNotNull() {
            addCriterion("morph_tag is not null");
            return (Criteria) this;
        }

        public Criteria andMorphTagEqualTo(String value) {
            addCriterion("morph_tag =", value, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagNotEqualTo(String value) {
            addCriterion("morph_tag <>", value, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagGreaterThan(String value) {
            addCriterion("morph_tag >", value, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagGreaterThanOrEqualTo(String value) {
            addCriterion("morph_tag >=", value, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagLessThan(String value) {
            addCriterion("morph_tag <", value, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagLessThanOrEqualTo(String value) {
            addCriterion("morph_tag <=", value, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagLike(String value) {
            addCriterion("morph_tag like", value, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagNotLike(String value) {
            addCriterion("morph_tag not like", value, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagIn(List<String> values) {
            addCriterion("morph_tag in", values, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagNotIn(List<String> values) {
            addCriterion("morph_tag not in", values, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagBetween(String value1, String value2) {
            addCriterion("morph_tag between", value1, value2, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagNotBetween(String value1, String value2) {
            addCriterion("morph_tag not between", value1, value2, "morphTag");
            return (Criteria) this;
        }

        public Criteria andNumberIsNull() {
            addCriterion("number is null");
            return (Criteria) this;
        }

        public Criteria andNumberIsNotNull() {
            addCriterion("number is not null");
            return (Criteria) this;
        }

        public Criteria andNumberEqualTo(String value) {
            addCriterion("number =", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotEqualTo(String value) {
            addCriterion("number <>", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThan(String value) {
            addCriterion("number >", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThanOrEqualTo(String value) {
            addCriterion("number >=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThan(String value) {
            addCriterion("number <", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThanOrEqualTo(String value) {
            addCriterion("number <=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLike(String value) {
            addCriterion("number like", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotLike(String value) {
            addCriterion("number not like", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberIn(List<String> values) {
            addCriterion("number in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotIn(List<String> values) {
            addCriterion("number not in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberBetween(String value1, String value2) {
            addCriterion("number between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotBetween(String value1, String value2) {
            addCriterion("number not between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("gender like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("gender not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andWordCaseIsNull() {
            addCriterion("word_case is null");
            return (Criteria) this;
        }

        public Criteria andWordCaseIsNotNull() {
            addCriterion("word_case is not null");
            return (Criteria) this;
        }

        public Criteria andWordCaseEqualTo(String value) {
            addCriterion("word_case =", value, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseNotEqualTo(String value) {
            addCriterion("word_case <>", value, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseGreaterThan(String value) {
            addCriterion("word_case >", value, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseGreaterThanOrEqualTo(String value) {
            addCriterion("word_case >=", value, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseLessThan(String value) {
            addCriterion("word_case <", value, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseLessThanOrEqualTo(String value) {
            addCriterion("word_case <=", value, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseLike(String value) {
            addCriterion("word_case like", value, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseNotLike(String value) {
            addCriterion("word_case not like", value, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseIn(List<String> values) {
            addCriterion("word_case in", values, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseNotIn(List<String> values) {
            addCriterion("word_case not in", values, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseBetween(String value1, String value2) {
            addCriterion("word_case between", value1, value2, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseNotBetween(String value1, String value2) {
            addCriterion("word_case not between", value1, value2, "wordCase");
            return (Criteria) this;
        }

        public Criteria andTenseIsNull() {
            addCriterion("tense is null");
            return (Criteria) this;
        }

        public Criteria andTenseIsNotNull() {
            addCriterion("tense is not null");
            return (Criteria) this;
        }

        public Criteria andTenseEqualTo(String value) {
            addCriterion("tense =", value, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseNotEqualTo(String value) {
            addCriterion("tense <>", value, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseGreaterThan(String value) {
            addCriterion("tense >", value, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseGreaterThanOrEqualTo(String value) {
            addCriterion("tense >=", value, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseLessThan(String value) {
            addCriterion("tense <", value, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseLessThanOrEqualTo(String value) {
            addCriterion("tense <=", value, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseLike(String value) {
            addCriterion("tense like", value, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseNotLike(String value) {
            addCriterion("tense not like", value, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseIn(List<String> values) {
            addCriterion("tense in", values, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseNotIn(List<String> values) {
            addCriterion("tense not in", values, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseBetween(String value1, String value2) {
            addCriterion("tense between", value1, value2, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseNotBetween(String value1, String value2) {
            addCriterion("tense not between", value1, value2, "tense");
            return (Criteria) this;
        }

        public Criteria andVoiceIsNull() {
            addCriterion("voice is null");
            return (Criteria) this;
        }

        public Criteria andVoiceIsNotNull() {
            addCriterion("voice is not null");
            return (Criteria) this;
        }

        public Criteria andVoiceEqualTo(String value) {
            addCriterion("voice =", value, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceNotEqualTo(String value) {
            addCriterion("voice <>", value, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceGreaterThan(String value) {
            addCriterion("voice >", value, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceGreaterThanOrEqualTo(String value) {
            addCriterion("voice >=", value, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceLessThan(String value) {
            addCriterion("voice <", value, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceLessThanOrEqualTo(String value) {
            addCriterion("voice <=", value, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceLike(String value) {
            addCriterion("voice like", value, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceNotLike(String value) {
            addCriterion("voice not like", value, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceIn(List<String> values) {
            addCriterion("voice in", values, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceNotIn(List<String> values) {
            addCriterion("voice not in", values, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceBetween(String value1, String value2) {
            addCriterion("voice between", value1, value2, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceNotBetween(String value1, String value2) {
            addCriterion("voice not between", value1, value2, "voice");
            return (Criteria) this;
        }

        public Criteria andMoodIsNull() {
            addCriterion("mood is null");
            return (Criteria) this;
        }

        public Criteria andMoodIsNotNull() {
            addCriterion("mood is not null");
            return (Criteria) this;
        }

        public Criteria andMoodEqualTo(String value) {
            addCriterion("mood =", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodNotEqualTo(String value) {
            addCriterion("mood <>", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodGreaterThan(String value) {
            addCriterion("mood >", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodGreaterThanOrEqualTo(String value) {
            addCriterion("mood >=", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodLessThan(String value) {
            addCriterion("mood <", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodLessThanOrEqualTo(String value) {
            addCriterion("mood <=", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodLike(String value) {
            addCriterion("mood like", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodNotLike(String value) {
            addCriterion("mood not like", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodIn(List<String> values) {
            addCriterion("mood in", values, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodNotIn(List<String> values) {
            addCriterion("mood not in", values, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodBetween(String value1, String value2) {
            addCriterion("mood between", value1, value2, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodNotBetween(String value1, String value2) {
            addCriterion("mood not between", value1, value2, "mood");
            return (Criteria) this;
        }

        public Criteria andStrongIsNull() {
            addCriterion("strong is null");
            return (Criteria) this;
        }

        public Criteria andStrongIsNotNull() {
            addCriterion("strong is not null");
            return (Criteria) this;
        }

        public Criteria andStrongEqualTo(Integer value) {
            addCriterion("strong =", value, "strong");
            return (Criteria) this;
        }

        public Criteria andStrongNotEqualTo(Integer value) {
            addCriterion("strong <>", value, "strong");
            return (Criteria) this;
        }

        public Criteria andStrongGreaterThan(Integer value) {
            addCriterion("strong >", value, "strong");
            return (Criteria) this;
        }

        public Criteria andStrongGreaterThanOrEqualTo(Integer value) {
            addCriterion("strong >=", value, "strong");
            return (Criteria) this;
        }

        public Criteria andStrongLessThan(Integer value) {
            addCriterion("strong <", value, "strong");
            return (Criteria) this;
        }

        public Criteria andStrongLessThanOrEqualTo(Integer value) {
            addCriterion("strong <=", value, "strong");
            return (Criteria) this;
        }

        public Criteria andStrongIn(List<Integer> values) {
            addCriterion("strong in", values, "strong");
            return (Criteria) this;
        }

        public Criteria andStrongNotIn(List<Integer> values) {
            addCriterion("strong not in", values, "strong");
            return (Criteria) this;
        }

        public Criteria andStrongBetween(Integer value1, Integer value2) {
            addCriterion("strong between", value1, value2, "strong");
            return (Criteria) this;
        }

        public Criteria andStrongNotBetween(Integer value1, Integer value2) {
            addCriterion("strong not between", value1, value2, "strong");
            return (Criteria) this;
        }

        public Criteria andLemmaIsNull() {
            addCriterion("lemma is null");
            return (Criteria) this;
        }

        public Criteria andLemmaIsNotNull() {
            addCriterion("lemma is not null");
            return (Criteria) this;
        }

        public Criteria andLemmaEqualTo(String value) {
            addCriterion("lemma =", value, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaNotEqualTo(String value) {
            addCriterion("lemma <>", value, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaGreaterThan(String value) {
            addCriterion("lemma >", value, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaGreaterThanOrEqualTo(String value) {
            addCriterion("lemma >=", value, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaLessThan(String value) {
            addCriterion("lemma <", value, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaLessThanOrEqualTo(String value) {
            addCriterion("lemma <=", value, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaLike(String value) {
            addCriterion("lemma like", value, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaNotLike(String value) {
            addCriterion("lemma not like", value, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaIn(List<String> values) {
            addCriterion("lemma in", values, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaNotIn(List<String> values) {
            addCriterion("lemma not in", values, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaBetween(String value1, String value2) {
            addCriterion("lemma between", value1, value2, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaNotBetween(String value1, String value2) {
            addCriterion("lemma not between", value1, value2, "lemma");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gnt_word
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 09 00:54:46 CDT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}