package org.bls.gnt.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.bls.gnt.db.model.GntBookBean;
import org.bls.gnt.db.model.GntBookBeanExample;

public interface GntBookBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    long countByExample(GntBookBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int deleteByExample(GntBookBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int insert(GntBookBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int insertSelective(GntBookBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    List<GntBookBean> selectByExample(GntBookBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    GntBookBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int updateByExampleSelective(@Param("record") GntBookBean record, @Param("example") GntBookBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int updateByExample(@Param("record") GntBookBean record, @Param("example") GntBookBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int updateByPrimaryKeySelective(GntBookBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int updateByPrimaryKey(GntBookBean record);
}