package org.bls.gnt.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.bls.gnt.db.model.GntLexiconBean;
import org.bls.gnt.db.model.GntLexiconBeanExample;

public interface GntLexiconBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_lexicon
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    long countByExample(GntLexiconBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_lexicon
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int deleteByExample(GntLexiconBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_lexicon
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_lexicon
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int insert(GntLexiconBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_lexicon
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int insertSelective(GntLexiconBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_lexicon
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    List<GntLexiconBean> selectByExample(GntLexiconBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_lexicon
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    GntLexiconBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_lexicon
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int updateByExampleSelective(@Param("record") GntLexiconBean record, @Param("example") GntLexiconBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_lexicon
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int updateByExample(@Param("record") GntLexiconBean record, @Param("example") GntLexiconBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_lexicon
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int updateByPrimaryKeySelective(GntLexiconBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_lexicon
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int updateByPrimaryKey(GntLexiconBean record);
}