package org.bls.gnt.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.bls.gnt.db.model.GntTextBean;
import org.bls.gnt.db.model.GntTextBeanExample;

public interface GntTextBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_text
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    long countByExample(GntTextBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_text
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int deleteByExample(GntTextBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_text
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_text
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int insert(GntTextBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_text
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int insertSelective(GntTextBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_text
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    List<GntTextBean> selectByExample(GntTextBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_text
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    GntTextBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_text
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int updateByExampleSelective(@Param("record") GntTextBean record, @Param("example") GntTextBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_text
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int updateByExample(@Param("record") GntTextBean record, @Param("example") GntTextBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_text
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int updateByPrimaryKeySelective(GntTextBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_text
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    int updateByPrimaryKey(GntTextBean record);
}