/*
 * Gnt API Docs!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Verse;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Chapter
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-03T04:08:05.303Z")
public class Chapter {
  @SerializedName("bookName")
  private String bookName = null;

  @SerializedName("totalVerse")
  private Integer totalVerse = null;

  @SerializedName("chapterNumber")
  private Integer chapterNumber = null;

  @SerializedName("verseList")
  private List<Verse> verseList = null;

  public Chapter bookName(String bookName) {
    this.bookName = bookName;
    return this;
  }

   /**
   * Get bookName
   * @return bookName
  **/
  @ApiModelProperty(value = "")
  public String getBookName() {
    return bookName;
  }

  public void setBookName(String bookName) {
    this.bookName = bookName;
  }

  public Chapter totalVerse(Integer totalVerse) {
    this.totalVerse = totalVerse;
    return this;
  }

   /**
   * Get totalVerse
   * @return totalVerse
  **/
  @ApiModelProperty(value = "")
  public Integer getTotalVerse() {
    return totalVerse;
  }

  public void setTotalVerse(Integer totalVerse) {
    this.totalVerse = totalVerse;
  }

  public Chapter chapterNumber(Integer chapterNumber) {
    this.chapterNumber = chapterNumber;
    return this;
  }

   /**
   * Get chapterNumber
   * @return chapterNumber
  **/
  @ApiModelProperty(value = "")
  public Integer getChapterNumber() {
    return chapterNumber;
  }

  public void setChapterNumber(Integer chapterNumber) {
    this.chapterNumber = chapterNumber;
  }

  public Chapter verseList(List<Verse> verseList) {
    this.verseList = verseList;
    return this;
  }

  public Chapter addVerseListItem(Verse verseListItem) {
    if (this.verseList == null) {
      this.verseList = new ArrayList<Verse>();
    }
    this.verseList.add(verseListItem);
    return this;
  }

   /**
   * Get verseList
   * @return verseList
  **/
  @ApiModelProperty(value = "")
  public List<Verse> getVerseList() {
    return verseList;
  }

  public void setVerseList(List<Verse> verseList) {
    this.verseList = verseList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Chapter chapter = (Chapter) o;
    return Objects.equals(this.bookName, chapter.bookName) &&
        Objects.equals(this.totalVerse, chapter.totalVerse) &&
        Objects.equals(this.chapterNumber, chapter.chapterNumber) &&
        Objects.equals(this.verseList, chapter.verseList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bookName, totalVerse, chapterNumber, verseList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Chapter {\n");
    
    sb.append("    bookName: ").append(toIndentedString(bookName)).append("\n");
    sb.append("    totalVerse: ").append(toIndentedString(totalVerse)).append("\n");
    sb.append("    chapterNumber: ").append(toIndentedString(chapterNumber)).append("\n");
    sb.append("    verseList: ").append(toIndentedString(verseList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

