/*
 * Gnt API Docs!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GntLexiconBean
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-03T04:08:05.303Z")
public class GntLexiconBean {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("word")
  private String word = null;

  @SerializedName("fullWord")
  private String fullWord = null;

  @SerializedName("meaning")
  private String meaning = null;

  @SerializedName("fullMeaning")
  private String fullMeaning = null;

  @SerializedName("wordType")
  private String wordType = null;

  @SerializedName("strongNumber")
  private Integer strongNumber = null;

  @SerializedName("frequency")
  private Integer frequency = null;

  public GntLexiconBean id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public GntLexiconBean word(String word) {
    this.word = word;
    return this;
  }

   /**
   * Get word
   * @return word
  **/
  @ApiModelProperty(value = "")
  public String getWord() {
    return word;
  }

  public void setWord(String word) {
    this.word = word;
  }

  public GntLexiconBean fullWord(String fullWord) {
    this.fullWord = fullWord;
    return this;
  }

   /**
   * Get fullWord
   * @return fullWord
  **/
  @ApiModelProperty(value = "")
  public String getFullWord() {
    return fullWord;
  }

  public void setFullWord(String fullWord) {
    this.fullWord = fullWord;
  }

  public GntLexiconBean meaning(String meaning) {
    this.meaning = meaning;
    return this;
  }

   /**
   * Get meaning
   * @return meaning
  **/
  @ApiModelProperty(value = "")
  public String getMeaning() {
    return meaning;
  }

  public void setMeaning(String meaning) {
    this.meaning = meaning;
  }

  public GntLexiconBean fullMeaning(String fullMeaning) {
    this.fullMeaning = fullMeaning;
    return this;
  }

   /**
   * Get fullMeaning
   * @return fullMeaning
  **/
  @ApiModelProperty(value = "")
  public String getFullMeaning() {
    return fullMeaning;
  }

  public void setFullMeaning(String fullMeaning) {
    this.fullMeaning = fullMeaning;
  }

  public GntLexiconBean wordType(String wordType) {
    this.wordType = wordType;
    return this;
  }

   /**
   * Get wordType
   * @return wordType
  **/
  @ApiModelProperty(value = "")
  public String getWordType() {
    return wordType;
  }

  public void setWordType(String wordType) {
    this.wordType = wordType;
  }

  public GntLexiconBean strongNumber(Integer strongNumber) {
    this.strongNumber = strongNumber;
    return this;
  }

   /**
   * Get strongNumber
   * @return strongNumber
  **/
  @ApiModelProperty(value = "")
  public Integer getStrongNumber() {
    return strongNumber;
  }

  public void setStrongNumber(Integer strongNumber) {
    this.strongNumber = strongNumber;
  }

  public GntLexiconBean frequency(Integer frequency) {
    this.frequency = frequency;
    return this;
  }

   /**
   * Get frequency
   * @return frequency
  **/
  @ApiModelProperty(value = "")
  public Integer getFrequency() {
    return frequency;
  }

  public void setFrequency(Integer frequency) {
    this.frequency = frequency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GntLexiconBean gntLexiconBean = (GntLexiconBean) o;
    return Objects.equals(this.id, gntLexiconBean.id) &&
        Objects.equals(this.word, gntLexiconBean.word) &&
        Objects.equals(this.fullWord, gntLexiconBean.fullWord) &&
        Objects.equals(this.meaning, gntLexiconBean.meaning) &&
        Objects.equals(this.fullMeaning, gntLexiconBean.fullMeaning) &&
        Objects.equals(this.wordType, gntLexiconBean.wordType) &&
        Objects.equals(this.strongNumber, gntLexiconBean.strongNumber) &&
        Objects.equals(this.frequency, gntLexiconBean.frequency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, word, fullWord, meaning, fullMeaning, wordType, strongNumber, frequency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GntLexiconBean {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    word: ").append(toIndentedString(word)).append("\n");
    sb.append("    fullWord: ").append(toIndentedString(fullWord)).append("\n");
    sb.append("    meaning: ").append(toIndentedString(meaning)).append("\n");
    sb.append("    fullMeaning: ").append(toIndentedString(fullMeaning)).append("\n");
    sb.append("    wordType: ").append(toIndentedString(wordType)).append("\n");
    sb.append("    strongNumber: ").append(toIndentedString(strongNumber)).append("\n");
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

