/*
 * Gnt API Docs!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Verse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-03T04:08:05.303Z")
public class Verse {
  @SerializedName("verseNumber")
  private Integer verseNumber = null;

  @SerializedName("verseText")
  private String verseText = null;

  public Verse verseNumber(Integer verseNumber) {
    this.verseNumber = verseNumber;
    return this;
  }

   /**
   * Get verseNumber
   * @return verseNumber
  **/
  @ApiModelProperty(value = "")
  public Integer getVerseNumber() {
    return verseNumber;
  }

  public void setVerseNumber(Integer verseNumber) {
    this.verseNumber = verseNumber;
  }

  public Verse verseText(String verseText) {
    this.verseText = verseText;
    return this;
  }

   /**
   * Get verseText
   * @return verseText
  **/
  @ApiModelProperty(value = "")
  public String getVerseText() {
    return verseText;
  }

  public void setVerseText(String verseText) {
    this.verseText = verseText;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Verse verse = (Verse) o;
    return Objects.equals(this.verseNumber, verse.verseNumber) &&
        Objects.equals(this.verseText, verse.verseText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(verseNumber, verseText);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Verse {\n");
    
    sb.append("    verseNumber: ").append(toIndentedString(verseNumber)).append("\n");
    sb.append("    verseText: ").append(toIndentedString(verseText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

