package org.bls.gnt.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.bls.gnt.db.model.GntBook;
import org.bls.gnt.db.model.GntBookExample;

public interface GntBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    long countByExample(GntBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    int deleteByExample(GntBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    int insert(GntBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    int insertSelective(GntBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    List<GntBook> selectByExample(GntBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    GntBook selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    int updateByExampleSelective(@Param("record") GntBook record, @Param("example") GntBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    int updateByExample(@Param("record") GntBook record, @Param("example") GntBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    int updateByPrimaryKeySelective(GntBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_book
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    int updateByPrimaryKey(GntBook record);
}