package org.bls.gnt.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.bls.gnt.db.model.GntWord;
import org.bls.gnt.db.model.GntWordExample;

public interface GntWordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    long countByExample(GntWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    int deleteByExample(GntWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    int insert(GntWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    int insertSelective(GntWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    List<GntWord> selectByExample(GntWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    GntWord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    int updateByExampleSelective(@Param("record") GntWord record, @Param("example") GntWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    int updateByExample(@Param("record") GntWord record, @Param("example") GntWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    int updateByPrimaryKeySelective(GntWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Mon Jul 23 11:44:47 CDT 2018
     */
    int updateByPrimaryKey(GntWord record);
}