package org.blem.greek.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.blem.greek.db.model.GntWordBean;
import org.blem.greek.db.model.GntWordBeanExample;

public interface GntWordBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    long countByExample(GntWordBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    int deleteByExample(GntWordBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    int insert(GntWordBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    int insertSelective(GntWordBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    List<GntWordBean> selectByExample(GntWordBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    GntWordBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    int updateByExampleSelective(@Param("record") GntWordBean record, @Param("example") GntWordBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    int updateByExample(@Param("record") GntWordBean record, @Param("example") GntWordBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    int updateByPrimaryKeySelective(GntWordBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Sat Jun 09 00:54:46 CDT 2018
     */
    int updateByPrimaryKey(GntWordBean record);
}