package org.bls.gnt.db.model;

public class GntTextBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.id
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.book_short_name
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String bookShortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.chapter_number
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private Integer chapterNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.verse_number
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private Integer verseNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.sequence_number
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private Integer sequenceNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.text
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.normalized_text
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String normalizedText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.lemma
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String lemma;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.part_of_speech
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String partOfSpeech;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.morph_tag
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String morphTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.person
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String person;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.number
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.gender
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.word_case
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String wordCase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.tense
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String tense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.voice
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String voice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.mood
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String mood;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.degree
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_text.strong
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private Integer strong;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.id
     *
     * @return the value of gnt_text.id
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.id
     *
     * @param id the value for gnt_text.id
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.book_short_name
     *
     * @return the value of gnt_text.book_short_name
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getBookShortName() {
        return bookShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.book_short_name
     *
     * @param bookShortName the value for gnt_text.book_short_name
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setBookShortName(String bookShortName) {
        this.bookShortName = bookShortName == null ? null : bookShortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.chapter_number
     *
     * @return the value of gnt_text.chapter_number
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public Integer getChapterNumber() {
        return chapterNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.chapter_number
     *
     * @param chapterNumber the value for gnt_text.chapter_number
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setChapterNumber(Integer chapterNumber) {
        this.chapterNumber = chapterNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.verse_number
     *
     * @return the value of gnt_text.verse_number
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public Integer getVerseNumber() {
        return verseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.verse_number
     *
     * @param verseNumber the value for gnt_text.verse_number
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setVerseNumber(Integer verseNumber) {
        this.verseNumber = verseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.sequence_number
     *
     * @return the value of gnt_text.sequence_number
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public Integer getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.sequence_number
     *
     * @param sequenceNumber the value for gnt_text.sequence_number
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setSequenceNumber(Integer sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.text
     *
     * @return the value of gnt_text.text
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.text
     *
     * @param text the value for gnt_text.text
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.word
     *
     * @return the value of gnt_text.word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.word
     *
     * @param word the value for gnt_text.word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.normalized_text
     *
     * @return the value of gnt_text.normalized_text
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getNormalizedText() {
        return normalizedText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.normalized_text
     *
     * @param normalizedText the value for gnt_text.normalized_text
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setNormalizedText(String normalizedText) {
        this.normalizedText = normalizedText == null ? null : normalizedText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.lemma
     *
     * @return the value of gnt_text.lemma
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getLemma() {
        return lemma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.lemma
     *
     * @param lemma the value for gnt_text.lemma
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setLemma(String lemma) {
        this.lemma = lemma == null ? null : lemma.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.part_of_speech
     *
     * @return the value of gnt_text.part_of_speech
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getPartOfSpeech() {
        return partOfSpeech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.part_of_speech
     *
     * @param partOfSpeech the value for gnt_text.part_of_speech
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setPartOfSpeech(String partOfSpeech) {
        this.partOfSpeech = partOfSpeech == null ? null : partOfSpeech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.morph_tag
     *
     * @return the value of gnt_text.morph_tag
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getMorphTag() {
        return morphTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.morph_tag
     *
     * @param morphTag the value for gnt_text.morph_tag
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setMorphTag(String morphTag) {
        this.morphTag = morphTag == null ? null : morphTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.person
     *
     * @return the value of gnt_text.person
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.person
     *
     * @param person the value for gnt_text.person
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setPerson(String person) {
        this.person = person == null ? null : person.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.number
     *
     * @return the value of gnt_text.number
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.number
     *
     * @param number the value for gnt_text.number
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.gender
     *
     * @return the value of gnt_text.gender
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.gender
     *
     * @param gender the value for gnt_text.gender
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.word_case
     *
     * @return the value of gnt_text.word_case
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getWordCase() {
        return wordCase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.word_case
     *
     * @param wordCase the value for gnt_text.word_case
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setWordCase(String wordCase) {
        this.wordCase = wordCase == null ? null : wordCase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.tense
     *
     * @return the value of gnt_text.tense
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getTense() {
        return tense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.tense
     *
     * @param tense the value for gnt_text.tense
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setTense(String tense) {
        this.tense = tense == null ? null : tense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.voice
     *
     * @return the value of gnt_text.voice
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getVoice() {
        return voice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.voice
     *
     * @param voice the value for gnt_text.voice
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setVoice(String voice) {
        this.voice = voice == null ? null : voice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.mood
     *
     * @return the value of gnt_text.mood
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getMood() {
        return mood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.mood
     *
     * @param mood the value for gnt_text.mood
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setMood(String mood) {
        this.mood = mood == null ? null : mood.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.degree
     *
     * @return the value of gnt_text.degree
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.degree
     *
     * @param degree the value for gnt_text.degree
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_text.strong
     *
     * @return the value of gnt_text.strong
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public Integer getStrong() {
        return strong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_text.strong
     *
     * @param strong the value for gnt_text.strong
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setStrong(Integer strong) {
        this.strong = strong;
    }
}