package org.bls.gnt.db.model;

import java.util.ArrayList;
import java.util.List;

public class GntWordBeanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gnt_word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gnt_word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gnt_word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public GntWordBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gnt_word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gnt_word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWordIsNull() {
            addCriterion("word is null");
            return (Criteria) this;
        }

        public Criteria andWordIsNotNull() {
            addCriterion("word is not null");
            return (Criteria) this;
        }

        public Criteria andWordEqualTo(String value) {
            addCriterion("word =", value, "word");
            return (Criteria) this;
        }

        public Criteria andWordNotEqualTo(String value) {
            addCriterion("word <>", value, "word");
            return (Criteria) this;
        }

        public Criteria andWordGreaterThan(String value) {
            addCriterion("word >", value, "word");
            return (Criteria) this;
        }

        public Criteria andWordGreaterThanOrEqualTo(String value) {
            addCriterion("word >=", value, "word");
            return (Criteria) this;
        }

        public Criteria andWordLessThan(String value) {
            addCriterion("word <", value, "word");
            return (Criteria) this;
        }

        public Criteria andWordLessThanOrEqualTo(String value) {
            addCriterion("word <=", value, "word");
            return (Criteria) this;
        }

        public Criteria andWordLike(String value) {
            addCriterion("word like", value, "word");
            return (Criteria) this;
        }

        public Criteria andWordNotLike(String value) {
            addCriterion("word not like", value, "word");
            return (Criteria) this;
        }

        public Criteria andWordIn(List<String> values) {
            addCriterion("word in", values, "word");
            return (Criteria) this;
        }

        public Criteria andWordNotIn(List<String> values) {
            addCriterion("word not in", values, "word");
            return (Criteria) this;
        }

        public Criteria andWordBetween(String value1, String value2) {
            addCriterion("word between", value1, value2, "word");
            return (Criteria) this;
        }

        public Criteria andWordNotBetween(String value1, String value2) {
            addCriterion("word not between", value1, value2, "word");
            return (Criteria) this;
        }

        public Criteria andLemmaIsNull() {
            addCriterion("lemma is null");
            return (Criteria) this;
        }

        public Criteria andLemmaIsNotNull() {
            addCriterion("lemma is not null");
            return (Criteria) this;
        }

        public Criteria andLemmaEqualTo(String value) {
            addCriterion("lemma =", value, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaNotEqualTo(String value) {
            addCriterion("lemma <>", value, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaGreaterThan(String value) {
            addCriterion("lemma >", value, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaGreaterThanOrEqualTo(String value) {
            addCriterion("lemma >=", value, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaLessThan(String value) {
            addCriterion("lemma <", value, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaLessThanOrEqualTo(String value) {
            addCriterion("lemma <=", value, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaLike(String value) {
            addCriterion("lemma like", value, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaNotLike(String value) {
            addCriterion("lemma not like", value, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaIn(List<String> values) {
            addCriterion("lemma in", values, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaNotIn(List<String> values) {
            addCriterion("lemma not in", values, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaBetween(String value1, String value2) {
            addCriterion("lemma between", value1, value2, "lemma");
            return (Criteria) this;
        }

        public Criteria andLemmaNotBetween(String value1, String value2) {
            addCriterion("lemma not between", value1, value2, "lemma");
            return (Criteria) this;
        }

        public Criteria andPartOfSpeechIsNull() {
            addCriterion("part_of_speech is null");
            return (Criteria) this;
        }

        public Criteria andPartOfSpeechIsNotNull() {
            addCriterion("part_of_speech is not null");
            return (Criteria) this;
        }

        public Criteria andPartOfSpeechEqualTo(String value) {
            addCriterion("part_of_speech =", value, "partOfSpeech");
            return (Criteria) this;
        }

        public Criteria andPartOfSpeechNotEqualTo(String value) {
            addCriterion("part_of_speech <>", value, "partOfSpeech");
            return (Criteria) this;
        }

        public Criteria andPartOfSpeechGreaterThan(String value) {
            addCriterion("part_of_speech >", value, "partOfSpeech");
            return (Criteria) this;
        }

        public Criteria andPartOfSpeechGreaterThanOrEqualTo(String value) {
            addCriterion("part_of_speech >=", value, "partOfSpeech");
            return (Criteria) this;
        }

        public Criteria andPartOfSpeechLessThan(String value) {
            addCriterion("part_of_speech <", value, "partOfSpeech");
            return (Criteria) this;
        }

        public Criteria andPartOfSpeechLessThanOrEqualTo(String value) {
            addCriterion("part_of_speech <=", value, "partOfSpeech");
            return (Criteria) this;
        }

        public Criteria andPartOfSpeechLike(String value) {
            addCriterion("part_of_speech like", value, "partOfSpeech");
            return (Criteria) this;
        }

        public Criteria andPartOfSpeechNotLike(String value) {
            addCriterion("part_of_speech not like", value, "partOfSpeech");
            return (Criteria) this;
        }

        public Criteria andPartOfSpeechIn(List<String> values) {
            addCriterion("part_of_speech in", values, "partOfSpeech");
            return (Criteria) this;
        }

        public Criteria andPartOfSpeechNotIn(List<String> values) {
            addCriterion("part_of_speech not in", values, "partOfSpeech");
            return (Criteria) this;
        }

        public Criteria andPartOfSpeechBetween(String value1, String value2) {
            addCriterion("part_of_speech between", value1, value2, "partOfSpeech");
            return (Criteria) this;
        }

        public Criteria andPartOfSpeechNotBetween(String value1, String value2) {
            addCriterion("part_of_speech not between", value1, value2, "partOfSpeech");
            return (Criteria) this;
        }

        public Criteria andMorphTagIsNull() {
            addCriterion("morph_tag is null");
            return (Criteria) this;
        }

        public Criteria andMorphTagIsNotNull() {
            addCriterion("morph_tag is not null");
            return (Criteria) this;
        }

        public Criteria andMorphTagEqualTo(String value) {
            addCriterion("morph_tag =", value, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagNotEqualTo(String value) {
            addCriterion("morph_tag <>", value, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagGreaterThan(String value) {
            addCriterion("morph_tag >", value, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagGreaterThanOrEqualTo(String value) {
            addCriterion("morph_tag >=", value, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagLessThan(String value) {
            addCriterion("morph_tag <", value, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagLessThanOrEqualTo(String value) {
            addCriterion("morph_tag <=", value, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagLike(String value) {
            addCriterion("morph_tag like", value, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagNotLike(String value) {
            addCriterion("morph_tag not like", value, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagIn(List<String> values) {
            addCriterion("morph_tag in", values, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagNotIn(List<String> values) {
            addCriterion("morph_tag not in", values, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagBetween(String value1, String value2) {
            addCriterion("morph_tag between", value1, value2, "morphTag");
            return (Criteria) this;
        }

        public Criteria andMorphTagNotBetween(String value1, String value2) {
            addCriterion("morph_tag not between", value1, value2, "morphTag");
            return (Criteria) this;
        }

        public Criteria andPersonIsNull() {
            addCriterion("person is null");
            return (Criteria) this;
        }

        public Criteria andPersonIsNotNull() {
            addCriterion("person is not null");
            return (Criteria) this;
        }

        public Criteria andPersonEqualTo(String value) {
            addCriterion("person =", value, "person");
            return (Criteria) this;
        }

        public Criteria andPersonNotEqualTo(String value) {
            addCriterion("person <>", value, "person");
            return (Criteria) this;
        }

        public Criteria andPersonGreaterThan(String value) {
            addCriterion("person >", value, "person");
            return (Criteria) this;
        }

        public Criteria andPersonGreaterThanOrEqualTo(String value) {
            addCriterion("person >=", value, "person");
            return (Criteria) this;
        }

        public Criteria andPersonLessThan(String value) {
            addCriterion("person <", value, "person");
            return (Criteria) this;
        }

        public Criteria andPersonLessThanOrEqualTo(String value) {
            addCriterion("person <=", value, "person");
            return (Criteria) this;
        }

        public Criteria andPersonLike(String value) {
            addCriterion("person like", value, "person");
            return (Criteria) this;
        }

        public Criteria andPersonNotLike(String value) {
            addCriterion("person not like", value, "person");
            return (Criteria) this;
        }

        public Criteria andPersonIn(List<String> values) {
            addCriterion("person in", values, "person");
            return (Criteria) this;
        }

        public Criteria andPersonNotIn(List<String> values) {
            addCriterion("person not in", values, "person");
            return (Criteria) this;
        }

        public Criteria andPersonBetween(String value1, String value2) {
            addCriterion("person between", value1, value2, "person");
            return (Criteria) this;
        }

        public Criteria andPersonNotBetween(String value1, String value2) {
            addCriterion("person not between", value1, value2, "person");
            return (Criteria) this;
        }

        public Criteria andNumberIsNull() {
            addCriterion("number is null");
            return (Criteria) this;
        }

        public Criteria andNumberIsNotNull() {
            addCriterion("number is not null");
            return (Criteria) this;
        }

        public Criteria andNumberEqualTo(String value) {
            addCriterion("number =", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotEqualTo(String value) {
            addCriterion("number <>", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThan(String value) {
            addCriterion("number >", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThanOrEqualTo(String value) {
            addCriterion("number >=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThan(String value) {
            addCriterion("number <", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThanOrEqualTo(String value) {
            addCriterion("number <=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLike(String value) {
            addCriterion("number like", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotLike(String value) {
            addCriterion("number not like", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberIn(List<String> values) {
            addCriterion("number in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotIn(List<String> values) {
            addCriterion("number not in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberBetween(String value1, String value2) {
            addCriterion("number between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotBetween(String value1, String value2) {
            addCriterion("number not between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("gender like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("gender not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andWordCaseIsNull() {
            addCriterion("word_case is null");
            return (Criteria) this;
        }

        public Criteria andWordCaseIsNotNull() {
            addCriterion("word_case is not null");
            return (Criteria) this;
        }

        public Criteria andWordCaseEqualTo(String value) {
            addCriterion("word_case =", value, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseNotEqualTo(String value) {
            addCriterion("word_case <>", value, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseGreaterThan(String value) {
            addCriterion("word_case >", value, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseGreaterThanOrEqualTo(String value) {
            addCriterion("word_case >=", value, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseLessThan(String value) {
            addCriterion("word_case <", value, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseLessThanOrEqualTo(String value) {
            addCriterion("word_case <=", value, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseLike(String value) {
            addCriterion("word_case like", value, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseNotLike(String value) {
            addCriterion("word_case not like", value, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseIn(List<String> values) {
            addCriterion("word_case in", values, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseNotIn(List<String> values) {
            addCriterion("word_case not in", values, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseBetween(String value1, String value2) {
            addCriterion("word_case between", value1, value2, "wordCase");
            return (Criteria) this;
        }

        public Criteria andWordCaseNotBetween(String value1, String value2) {
            addCriterion("word_case not between", value1, value2, "wordCase");
            return (Criteria) this;
        }

        public Criteria andTenseIsNull() {
            addCriterion("tense is null");
            return (Criteria) this;
        }

        public Criteria andTenseIsNotNull() {
            addCriterion("tense is not null");
            return (Criteria) this;
        }

        public Criteria andTenseEqualTo(String value) {
            addCriterion("tense =", value, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseNotEqualTo(String value) {
            addCriterion("tense <>", value, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseGreaterThan(String value) {
            addCriterion("tense >", value, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseGreaterThanOrEqualTo(String value) {
            addCriterion("tense >=", value, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseLessThan(String value) {
            addCriterion("tense <", value, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseLessThanOrEqualTo(String value) {
            addCriterion("tense <=", value, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseLike(String value) {
            addCriterion("tense like", value, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseNotLike(String value) {
            addCriterion("tense not like", value, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseIn(List<String> values) {
            addCriterion("tense in", values, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseNotIn(List<String> values) {
            addCriterion("tense not in", values, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseBetween(String value1, String value2) {
            addCriterion("tense between", value1, value2, "tense");
            return (Criteria) this;
        }

        public Criteria andTenseNotBetween(String value1, String value2) {
            addCriterion("tense not between", value1, value2, "tense");
            return (Criteria) this;
        }

        public Criteria andVoiceIsNull() {
            addCriterion("voice is null");
            return (Criteria) this;
        }

        public Criteria andVoiceIsNotNull() {
            addCriterion("voice is not null");
            return (Criteria) this;
        }

        public Criteria andVoiceEqualTo(String value) {
            addCriterion("voice =", value, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceNotEqualTo(String value) {
            addCriterion("voice <>", value, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceGreaterThan(String value) {
            addCriterion("voice >", value, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceGreaterThanOrEqualTo(String value) {
            addCriterion("voice >=", value, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceLessThan(String value) {
            addCriterion("voice <", value, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceLessThanOrEqualTo(String value) {
            addCriterion("voice <=", value, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceLike(String value) {
            addCriterion("voice like", value, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceNotLike(String value) {
            addCriterion("voice not like", value, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceIn(List<String> values) {
            addCriterion("voice in", values, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceNotIn(List<String> values) {
            addCriterion("voice not in", values, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceBetween(String value1, String value2) {
            addCriterion("voice between", value1, value2, "voice");
            return (Criteria) this;
        }

        public Criteria andVoiceNotBetween(String value1, String value2) {
            addCriterion("voice not between", value1, value2, "voice");
            return (Criteria) this;
        }

        public Criteria andMoodIsNull() {
            addCriterion("mood is null");
            return (Criteria) this;
        }

        public Criteria andMoodIsNotNull() {
            addCriterion("mood is not null");
            return (Criteria) this;
        }

        public Criteria andMoodEqualTo(String value) {
            addCriterion("mood =", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodNotEqualTo(String value) {
            addCriterion("mood <>", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodGreaterThan(String value) {
            addCriterion("mood >", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodGreaterThanOrEqualTo(String value) {
            addCriterion("mood >=", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodLessThan(String value) {
            addCriterion("mood <", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodLessThanOrEqualTo(String value) {
            addCriterion("mood <=", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodLike(String value) {
            addCriterion("mood like", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodNotLike(String value) {
            addCriterion("mood not like", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodIn(List<String> values) {
            addCriterion("mood in", values, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodNotIn(List<String> values) {
            addCriterion("mood not in", values, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodBetween(String value1, String value2) {
            addCriterion("mood between", value1, value2, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodNotBetween(String value1, String value2) {
            addCriterion("mood not between", value1, value2, "mood");
            return (Criteria) this;
        }

        public Criteria andDegreeIsNull() {
            addCriterion("degree is null");
            return (Criteria) this;
        }

        public Criteria andDegreeIsNotNull() {
            addCriterion("degree is not null");
            return (Criteria) this;
        }

        public Criteria andDegreeEqualTo(String value) {
            addCriterion("degree =", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeNotEqualTo(String value) {
            addCriterion("degree <>", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeGreaterThan(String value) {
            addCriterion("degree >", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeGreaterThanOrEqualTo(String value) {
            addCriterion("degree >=", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeLessThan(String value) {
            addCriterion("degree <", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeLessThanOrEqualTo(String value) {
            addCriterion("degree <=", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeLike(String value) {
            addCriterion("degree like", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeNotLike(String value) {
            addCriterion("degree not like", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeIn(List<String> values) {
            addCriterion("degree in", values, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeNotIn(List<String> values) {
            addCriterion("degree not in", values, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeBetween(String value1, String value2) {
            addCriterion("degree between", value1, value2, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeNotBetween(String value1, String value2) {
            addCriterion("degree not between", value1, value2, "degree");
            return (Criteria) this;
        }

        public Criteria andFrequencyIsNull() {
            addCriterion("frequency is null");
            return (Criteria) this;
        }

        public Criteria andFrequencyIsNotNull() {
            addCriterion("frequency is not null");
            return (Criteria) this;
        }

        public Criteria andFrequencyEqualTo(Integer value) {
            addCriterion("frequency =", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyNotEqualTo(Integer value) {
            addCriterion("frequency <>", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyGreaterThan(Integer value) {
            addCriterion("frequency >", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyGreaterThanOrEqualTo(Integer value) {
            addCriterion("frequency >=", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyLessThan(Integer value) {
            addCriterion("frequency <", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyLessThanOrEqualTo(Integer value) {
            addCriterion("frequency <=", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyIn(List<Integer> values) {
            addCriterion("frequency in", values, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyNotIn(List<Integer> values) {
            addCriterion("frequency not in", values, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyBetween(Integer value1, Integer value2) {
            addCriterion("frequency between", value1, value2, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyNotBetween(Integer value1, Integer value2) {
            addCriterion("frequency not between", value1, value2, "frequency");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gnt_word
     *
     * @mbg.generated do_not_delete_during_merge Fri Nov 02 19:59:08 CDT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gnt_word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}