package org.bls.gnt.db.model;

public class GntWordBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_word.id
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_word.word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_word.lemma
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String lemma;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_word.part_of_speech
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String partOfSpeech;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_word.morph_tag
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String morphTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_word.person
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String person;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_word.number
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_word.gender
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_word.word_case
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String wordCase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_word.tense
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String tense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_word.voice
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String voice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_word.mood
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String mood;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_word.degree
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gnt_word.frequency
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    private Integer frequency;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_word.id
     *
     * @return the value of gnt_word.id
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_word.id
     *
     * @param id the value for gnt_word.id
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_word.word
     *
     * @return the value of gnt_word.word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_word.word
     *
     * @param word the value for gnt_word.word
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_word.lemma
     *
     * @return the value of gnt_word.lemma
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getLemma() {
        return lemma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_word.lemma
     *
     * @param lemma the value for gnt_word.lemma
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setLemma(String lemma) {
        this.lemma = lemma == null ? null : lemma.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_word.part_of_speech
     *
     * @return the value of gnt_word.part_of_speech
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getPartOfSpeech() {
        return partOfSpeech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_word.part_of_speech
     *
     * @param partOfSpeech the value for gnt_word.part_of_speech
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setPartOfSpeech(String partOfSpeech) {
        this.partOfSpeech = partOfSpeech == null ? null : partOfSpeech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_word.morph_tag
     *
     * @return the value of gnt_word.morph_tag
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getMorphTag() {
        return morphTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_word.morph_tag
     *
     * @param morphTag the value for gnt_word.morph_tag
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setMorphTag(String morphTag) {
        this.morphTag = morphTag == null ? null : morphTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_word.person
     *
     * @return the value of gnt_word.person
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_word.person
     *
     * @param person the value for gnt_word.person
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setPerson(String person) {
        this.person = person == null ? null : person.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_word.number
     *
     * @return the value of gnt_word.number
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_word.number
     *
     * @param number the value for gnt_word.number
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_word.gender
     *
     * @return the value of gnt_word.gender
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_word.gender
     *
     * @param gender the value for gnt_word.gender
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_word.word_case
     *
     * @return the value of gnt_word.word_case
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getWordCase() {
        return wordCase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_word.word_case
     *
     * @param wordCase the value for gnt_word.word_case
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setWordCase(String wordCase) {
        this.wordCase = wordCase == null ? null : wordCase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_word.tense
     *
     * @return the value of gnt_word.tense
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getTense() {
        return tense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_word.tense
     *
     * @param tense the value for gnt_word.tense
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setTense(String tense) {
        this.tense = tense == null ? null : tense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_word.voice
     *
     * @return the value of gnt_word.voice
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getVoice() {
        return voice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_word.voice
     *
     * @param voice the value for gnt_word.voice
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setVoice(String voice) {
        this.voice = voice == null ? null : voice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_word.mood
     *
     * @return the value of gnt_word.mood
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getMood() {
        return mood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_word.mood
     *
     * @param mood the value for gnt_word.mood
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setMood(String mood) {
        this.mood = mood == null ? null : mood.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_word.degree
     *
     * @return the value of gnt_word.degree
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_word.degree
     *
     * @param degree the value for gnt_word.degree
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gnt_word.frequency
     *
     * @return the value of gnt_word.frequency
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public Integer getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gnt_word.frequency
     *
     * @param frequency the value for gnt_word.frequency
     *
     * @mbg.generated Fri Nov 02 19:59:08 CDT 2018
     */
    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }
}